language: ruby

services:
  - docker

before_install:
- docker pull niccokunzmann/ci-latex

script:
- pdf/build.sh

deploy:
  provider: releases
  api_key:
    secure: "Ffzf9rDPWmfC0akTtwBOxMAGFvGUMXt8teeDdUasDCYa/6DoL5daMeuBD7ioDjmtBAQMyKgBCwFQx8RbTZSpXgUut2r4fIxTqX6kjnrZ7jjtsZDl29e7jZLmx0XGWJFIt3L7CJnyDWV/ElQP/5/f0eIyHWol+vN4rYqwg/Sv8zxtPPL5Au1FYwGEq958nDQKugrNxL3mGpQYmeLxJh3mdkFJPdnQZ+eD4UuMSyPhgZ1/Zxvfu0KR7emoM6LpB/2C1Bu5SyyyzLqpMa5B8VpiYAVDx3kmWRrUEz470u91+OAjds8KN+LqDHiuBYltevZ6qVkz45AES0uW6SUNRtZRE5THh0p8/6VbP0D7SMPQwE8N8ocXdYzeagPVxKSGx4NlvzknlRej3JjARSRM8Svk6/zakgxXueE3cwzGl9fEgdKDKsQizBsnNZGBuX4ApsShZGfNXZn8H0ExscL5220TxHZhDJbg/sSQvGjFHULRuUg4Qr+AIOKea5hwi1oKdCLt4JlX8nXdTxC7jl1Q9j4XmJmCvq3Jqmh3YYSsq0xGO1WVSUfynFxsxIrn5FMb9AxYx7ZOmtfW0OcLtGq4vMdhWhcqhH1d4S+d5bdLunKucubHXStHXsx6dzWjgT1xlxRAaWWRvKg4IG//0GQRjZixNEwnDgUnNu1F70IKyJ4B/l8="
  file_glob: true
  file:
  - pdf/books/*
  skip_cleanup: true

